name:                numeric-dictionary
version:             0.1.0.0
github:              "https://github.com/contrerasmiguel/numeric-dictionary.hs"
license:             BSD3
author:              "Miguel Contreras"
maintainer:          "migueldevelop@gmail.com"
copyright:           "2019 Miguel Contreras"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/contrerasmiguel/numeric-dictionary#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec == 3.1.13.0
  - filepath == 1.4.2.1
  - optparse-applicative == 0.14.3.0

library:
  source-dirs: src

executables:
  numeric-dictionary-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - numeric-dictionary

tests:
  numeric-dictionary-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - numeric-dictionary
